[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["python -m pip install -r api/requirements.txt"]

[start]
cmd = "cd api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
